name: client
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: ./my-agora-states-client
      - name: Build
        run: npm run build
        working-directory: ./my-agora-states-client
      - name: SHOW AWS CLI VERSION
        run: |
            aws --version
      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${AKIASEBV4CULME56VRLX}
          AWS_SECRET_ACCESS_KEY: ${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}
          AWS_EC2_METADATA_DISABLED: true
        run: |
            aws s3 sync
            --region ap-northeast-2
            ./my-agora-states-client/build s3://fe-8-shun-is-me-s3
            --delete
        working-directory: ./my-agora-states-client